<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Sutil DSL for Bulma CSS framework</Description>
        <TargetFramework>netstandard2.0</TargetFramework>
        <FablePackageType>library</FablePackageType>
        <PackageTags>fable-javascript</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Bulma.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Sutil\Sutil.fsproj" />
    </ItemGroup>
</Project>