<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>HTML DSL for Sutil</Description>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Media.fs" />
        <Compile Include="Svg.fs" />
        <Compile Include="Html.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Sutil\Sutil.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fable.Browser.Dom" />
        <PackageReference Include="Fable.Browser.MediaQueryList" />
        <PackageReference Include="Feliz.Engine" />
        <PackageReference Include="Feliz.Engine.Event" />
    </ItemGroup>
</Project>