<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Front-end framework for Fable</Description>
        <TargetFramework>netstandard2.0</TargetFramework>
        <FablePackageType>library</FablePackageType>
        <PackageTags>fable-javascript</PackageTags>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Helpers.fs" />
        <Compile Include="Log.fs" />
        <Compile Include="Internal.fs" />
        <Compile Include="Types.fs" />
        <Compile Include="StyleDomHelpers.fs" />
        <Compile Include="EventHelpers.fs" />
        <Compile Include="Store.fs" />
        <Compile Include="Elmish.fs" />
        <Compile Include="VirtualDom.fs" />
        <Compile Include="Patch.fs" />
        <Compile Include="Core.fs" />
        <Compile Include="ResizeObserver.fs" />
        <Compile Include="CoreElements.fs" />
        <Compile Include="Bindings.fs" />
        <Compile Include="Bind.fs" />
        <Compile Include="Styling.fs" />
        <Compile Include="Navigable.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fable.Browser.Css" />
        <PackageReference Include="Fable.Browser.Dom" />
        <PackageReference Include="Fable.Core" />
        <PackageReference Include="Fable.Promise" />
    </ItemGroup>
</Project>